
[pytest]

# Specifies that tests are contained in the 'tests' folder
testpaths = tests

# Options for code coverage reporting using pytest-cov plugin
# '--cov=main' option specifies that coverage should be measured for the 'main' module.
# '--cov-report=term-missing' option shows missing lines in the terminal output.
# '--cov-report=html' option generates an HTML report of the coverage results.
addopts = --cov=main --cov-report=term-missing --cov-report=html

# Automatically discover test files matching: 'test_*.py' or '*_test.py'
python_files = test_*.py *_test.py

# Define the naming convention for test classes and functions
python_classes = Test*

# Define the naming convention for test functions
python_functions = test_*

# Custom markers for categorizing tests
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    fast: marks tests as fast (deselect with '-m "not fast"')